name: resiruler-clean
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11.9
  - numpy=1.26.4
  - pandas=2.3.1
  - matplotlib=3.10.0
  - biopython=1.85
  - scipy=1.16.0
  - altair=5.5.0
  - pyarrow=13.0.0
  - usalign=20241201
  - streamlit=1.47.0
  - plotly=6.0.1
  - pip
  - pip:
    - molviewspec==1.6.0
    - py3dmol==2.5.2
